apiVersion: v1
kind: Namespace
metadata:
  name: anomaly-detection
  labels:
    name: anomaly-detection
    environment: "{{ .Values.global.environment | default "dev" }}"
    managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: streaming
  labels:
    name: streaming